import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import Navigation from "@/Components/nav/page";
import Footer from "@/Components/footer/page";
import QueryProvider from "@/providers/QueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Shopyfy Themes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // console.log(process.env.THEME_API);

  return (
    <html lang="en" className={inter.className}>
      <body>
        <NextUIProvider>
          <QueryProvider>
            <Navigation />

            {children}
            <Footer />
          </QueryProvider>
        </NextUIProvider>
      </body>
    </html>
  );
}
